### ISSUE TITLE
IP History Plugin Causes 1064 Error..

### ISSUE THREAD

**Issue by UnoNYC** [JeremyCrookshank/IP_History_Logs#18] opened 2021-04-22 07:26 UTC
Hi, I recently updated my forum to the latest version of MyBB, and since then, I have been getting a 1064 error whenever I try to visit the forum.

I deactivated the plugin, which fixed the issue and when I updated it and installed the newer version (1.3.0 => 1.4.1) I got the same error.

![photo_2021-04-22_03-19-19](https://user-images.githubusercontent.com/65578710/115673277-73127a00-a31a-11eb-9611-d3b22d07be37.jpg)

Can this issue be fixed?

Thank you in advance for your time, and I look forward to hearing from you very soon.

**Comment by JeremyCrookshank** [comment] 2021-04-22 07:31
Hey there, that's an odd issue, can you copy me that IP address bit here please(bit with the "?0'?)

Are you running MyBB locally or anything unusual?

**Comment by UnoNYC** [comment] 2021-04-24 20:23
Hi, thank you for the reply, and I apologize for the late response.. 

Anyway, I was running MyBB on the host itself.. (no clue on how to do so locally..)

I deactivated the plugin but I will reactivate it and copy the error message to text.

**Comment by JeremyCrookshank** [comment] 2021-04-24 20:32
And can you confirm this only started happening when you updated MyBB? Was it working before?

**Comment by UnoNYC** [comment] 2021-04-25 08:47
Yes. It was working before I upgraded to the latest version of MyBB. I noticed it also caused a SQL error when I was performing the update to the latest version, but it didn't seem to interfere with the installation, so I continued on.

When I got back to the index I logged into the ACP and turned off the plugin and turned it back on and  that was when it gave me the error again. I initially got the error when I tried acessing the forum from my phone.

Anyway I just reactivated the plugin and I dont get the error now,  so I will wait and see what happens once the cache updates itself, and if the error appears again, then I'll be able to copy the text for it like you previously requested.

Thank you for the responses and help so far and if it happens again I'll update this post.

**Comment by pgidave** [comment] 2021-05-19 18:02
I have a user who just reported this issue also.  I'm on myBB 1.8.24 and User IP History Logs_#8_stable.zip

Any ideas how to clear it without turning off the functionality?  Thanks

MyBB SQL Error
MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1064 - You have an error in your SQL syntax; check the manual that 
corresponds to your MySQL server version for the right syntax to use 
near '67'' at line 1
Query:
SELECT COUNT(*) as 'unique' FROM mybb_ip_history WHERE IP='/  \' AND uid='67'
If you're a visitor of this website, please wait a few minutes and try again. If this problem persists, please contact the site owner.

If you are the site owner, please check the MyBB Documentation for help resolving common issues, or get technical help on the MyBB Community Forums.

**Comment by JeremyCrookshank** [comment] 2021-05-20 07:32
Did it just occur or have you updated anything ie MyBB or the plugin? Also just checking you replaced the IP with a backslash as well?

**Comment by pgidave** [comment] 2021-05-20 13:44
It just occurred - I haven't updated anything in myBB for a few months.

Message above is just a paste of the text the user sent.  He also posted a screen shot, which I'm pasting in.  It looks like some non-ASCI characters.are in the string - so they didn't come out in the cut and paste.

Apparently, some other users have seen this too but didn't mention anything.

![image](https://user-images.githubusercontent.com/36483286/118989275-c0443480-b936-11eb-90fc-d383adacaad0.png)

**Comment by JeremyCrookshank** [comment] 2021-05-20 14:27
Thanks for the info. I believe i'll have a fix deployed for this very soon.

**Comment by pgidave** [comment] 2021-05-20 15:09
Great thanks.

**Comment by JeremyCrookshank** [comment] 2021-05-20 20:29
Can you please try using the new version on the dev branch(https://github.com/JeremyCrookshank/IP_History_Logs/tree/dev) 

It should fix you problems. Please let me know and I'll push it to live afterwards asap

**Comment by pgidave** [comment] 2021-05-21 01:44
Thanks!  I'll try to install tonight and have the users test tomorrow and let you know


________________________________

**Comment by pgidave** [comment] 2021-05-21 15:44
I've applied the patches - will let you know what the users say.

I do now get this in the logs:

<strong style="box-sizing: inherit; font-weight: 700; line-height: inherit; color: rgb(10, 10, 10); font-family: &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Warning</strong><span style="color: rgb(10, 10, 10); font-family: &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span>&nbsp;</span>[2] Use of undefined constant isValid - assumed 'isValid' (this will throw an Error in a future version of PHP) - Line: 75 - File: admin/modules/tools/ip_history_logs.php PHP 7.4.13 (FreeBSD)</span><br style="box-sizing: inherit; color: rgb(10, 10, 10); font-family: &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
File | Line | Function
-- | -- | --
/admin/modules/tools/ip_history_logs.php | 75 | errorHandler-&gt;error
/admin/modules/tools/ip_history_logs.php | 150 | HandleIP
/admin/index.php | 824 | require

**Comment by JeremyCrookshank** [comment] 2021-05-21 15:47
Make sure you have the latest commit as I did a minor change afterwards which would fix that(if you get latest from that branch now it should be resolved) as not sure when you got the changes

**Comment by pgidave** [comment] 2021-05-21 15:51
I just pulled from dev about 20 minutes ago.  I see it's just been updated - I'll reapply.

**Comment by JeremyCrookshank** [comment] 2021-05-21 15:53
My bad thought I'd changed that last night just pushed a new commit sorry
again 😆

**Comment by pgidave** [comment] 2021-05-21 16:05
No problem - just reinstalled and it looks better.

I'll let you know if any users have issues.  Many thanks for the great support.

**Comment by pgidave** [comment] 2021-05-21 17:18
The user who reported the issue on my screen dump above says the patch is working on his setup.

The other reports were from a few people who were having an issue when using  wifi at the hotels they were staying in - so no way to get them to reproduce it.

Thanks again.

**Comment by JeremyCrookshank** [comment] 2021-05-23 08:59
Excellent, I'm pretty happy that this will fix the issue so will push to main branch and publish on MyBB. Thanks again for the report/testing guys.

**Closed as completed by JeremyCrookshank** 2021-05-23 08:59 UTC
Labels: help wanted
